### ISSUE TITLE
Where is the application?

### ISSUE THREAD

**Issue by arrrrr444** [dreamscached/herokude#2]
Where is the application?
![Screenshot_2022-03-04-04-27-51](https://user-images.githubusercontent.com/77874962/156656493-29cb9031-455e-4b24-bbc1-4d98e91bb432.png)

**Comment by dreamscached** [comment]
`master` branch has no applications and comes as bare desktop environment. Check out `xterm` branch (comes with xterm, correspondingly) or `minimal` (firefox, eye of gnome, gnome-terminal, so on.)

Follow [this link](https://heroku.com/deploy?template=https://github.com/dreamscached/herokude/tree/minimal) if you want to deploy `minimal`, for example.
